Integrate new icon for TIDAL
elax46/custom-brand-icons pull request #231
Opened 2022-08-08 20:46 UTC by myopenflixr

Updated custom-brand-icons.js.
Added tidal-logo.svg to icon-svg folder
Added icon to README.md

2022-08-08 20:48 UTC, myopenflixr commented
This is my first ever github contribution. Hoping I did everything correctly!

2022-08-09 10:36 UTC, elax46 requested changes
Why are there several icons deleted and then added? the pull must contain only the three modified files nothing else

2022-08-09 10:36 UTC, elax46 commented on README.md
> +
Eliminate this change as in the last commit yesterday I already proceeded to insert a warning on pull requests

2022-08-09 13:17 UTC, myopenflixr commented on README.md
> +
I have no idea how that happened. I pulled from the dev branch and only modified the three files. Very strange to see all the deletions and additions. I swear I didn't modify those!

Can you just cancel this request so I can start over and open a new pull request? This is my first time attempting to contribute to a github project, so this is all new to me.

Once this is cancelled so I can start fresh, should I pull from dev or master?

2022-08-09 15:38 UTC, elax46 commented on README.md
> +
if the changes have been made in your fork, just reopen a pull request, remember to delete what I indicated first

2022-08-09 15:38 UTC, closed without merging